// Museo's musicological atlas: style definitions spanning eras and cultures.
// Each entry encodes what makes the style sound like itself: tempo, scales,
// harmonic language, rhythm, instrumentation, arrangement habits, form.

import type { ScaleName } from "./theory";

export type InstrumentId =
  | "subBass"
  | "bass808"
  | "pluckBass"
  | "uprightBass"
  | "fingerBass"
  | "piano"
  | "epiano"
  | "organ"
  | "harpsichord"
  | "nylonGuitar"
  | "steelGuitar"
  | "distGuitar"
  | "strings"
  | "staccatoStrings"
  | "brass"
  | "flute"
  | "panFlute"
  | "violin"
  | "trumpet"
  | "sax"
  | "sitar"
  | "koto"
  | "kalimba"
  | "marimba"
  | "bell"
  | "gamelanMetal"
  | "padWarm"
  | "padGlass"
  | "padChoir"
  | "leadSaw"
  | "leadSquare"
  | "leadChip"
  | "leadPluck"
  | "tanpura"
  | "accordion"
  | "harp";

export type ChordStyle =
  | "sustained"
  | "stabs"
  | "offbeat"
  | "arpeggiated"
  | "alberti"
  | "comping"
  | "strummed"
  | "pulsing";

export type BassStyle =
  | "root"
  | "rootFifth"
  | "walking"
  | "octaves"
  | "syncopated"
  | "sub"
  | "drone"
  | "montuno";

export type SectionType =
  | "intro"
  | "verse"
  | "prechorus"
  | "chorus"
  | "bridge"
  | "solo"
  | "breakdown"
  | "drop"
  | "outro";

export type StructureName = "song" | "songShort" | "edm" | "throughComposed" | "ambient" | "jazz" | "blues";

export const STRUCTURES: Record<StructureName, { type: SectionType; bars: number }[]> = {
  song: [
    { type: "intro", bars: 4 },
    { type: "verse", bars: 8 },
    { type: "prechorus", bars: 4 },
    { type: "chorus", bars: 8 },
    { type: "verse", bars: 8 },
    { type: "prechorus", bars: 4 },
    { type: "chorus", bars: 8 },
    { type: "bridge", bars: 8 },
    { type: "chorus", bars: 8 },
    { type: "outro", bars: 4 },
  ],
  songShort: [
    { type: "intro", bars: 4 },
    { type: "verse", bars: 8 },
    { type: "chorus", bars: 8 },
    { type: "verse", bars: 8 },
    { type: "chorus", bars: 8 },
    { type: "outro", bars: 4 },
  ],
  edm: [
    { type: "intro", bars: 8 },
    { type: "verse", bars: 8 },
    { type: "breakdown", bars: 8 },
    { type: "drop", bars: 16 },
    { type: "verse", bars: 8 },
    { type: "breakdown", bars: 8 },
    { type: "drop", bars: 16 },
    { type: "outro", bars: 8 },
  ],
  throughComposed: [
    { type: "intro", bars: 4 },
    { type: "verse", bars: 8 },
    { type: "chorus", bars: 8 },
    { type: "solo", bars: 8 },
    { type: "chorus", bars: 8 },
    { type: "outro", bars: 4 },
  ],
  ambient: [
    { type: "intro", bars: 8 },
    { type: "verse", bars: 16 },
    { type: "chorus", bars: 16 },
    { type: "verse", bars: 16 },
    { type: "outro", bars: 8 },
  ],
  jazz: [
    { type: "intro", bars: 4 },
    { type: "verse", bars: 16 }, // head
    { type: "solo", bars: 16 },
    { type: "solo", bars: 16 },
    { type: "verse", bars: 16 }, // head out
    { type: "outro", bars: 4 },
  ],
  blues: [
    { type: "intro", bars: 4 },
    { type: "verse", bars: 12 },
    { type: "verse", bars: 12 },
    { type: "solo", bars: 12 },
    { type: "verse", bars: 12 },
    { type: "outro", bars: 4 },
  ],
};

export interface GenreDef {
  id: string;
  name: string;
  era: string;
  years: string;
  region: string;
  description: string;
  keywords: string[];
  bpm: [number, number];
  swing?: number;
  stepsPerBar?: number; // 16 (4/4) by default, 12 = 3/4
  scales: ScaleName[];
  progressions: string[];
  drums: string[];
  instruments: {
    bass?: InstrumentId[];
    chords?: InstrumentId[];
    melody: InstrumentId[];
    pad?: InstrumentId[];
    arp?: InstrumentId[];
    drone?: InstrumentId[];
  };
  chordStyle: ChordStyle[];
  bassStyle: BassStyle[];
  arpChance?: number;
  padChance?: number;
  structures: StructureName[];
  vocalStyle: "none" | "lead" | "choir" | "chant";
  energy: number; // 0..1 baseline
  hue: number; // UI / video theming
}

export const GENRES: GenreDef[] = [
  {
    id: "gregorian",
    name: "Chant grégorien",
    era: "Moyen Âge",
    years: "~600–1100",
    region: "Europe",
    description: "Monodie sacrée a cappella, modes ecclésiastiques, longues phrases planantes dans la pierre des abbayes.",
    keywords: ["gregorian", "chant", "monastère", "sacré", "moine", "médiéval", "abbaye", "latin"],
    bpm: [55, 70],
    scales: ["dorian", "phrygian", "mixolydian"],
    progressions: ["modalDrone"],
    drums: ["none"],
    instruments: { melody: ["padChoir"], drone: ["padChoir"], pad: ["padChoir"] },
    chordStyle: ["sustained"],
    bassStyle: ["drone"],
    padChance: 1,
    structures: ["ambient"],
    vocalStyle: "chant",
    energy: 0.12,
    hue: 36,
  },
  {
    id: "medieval",
    name: "Estampie médiévale",
    era: "Moyen Âge",
    years: "1100–1400",
    region: "Europe",
    description: "Danse de troubadours : vièle et flûte sur bourdon, tambourin entêtant, modes anciens.",
    keywords: ["médiéval", "troubadour", "estampie", "taverne", "château", "fête médiévale"],
    bpm: [100, 124],
    scales: ["dorian", "mixolydian"],
    progressions: ["modalDrone", "folk"],
    drums: ["march"],
    instruments: { melody: ["flute", "violin"], drone: ["strings"], chords: ["nylonGuitar"] },
    chordStyle: ["strummed"],
    bassStyle: ["drone"],
    structures: ["throughComposed"],
    vocalStyle: "lead",
    energy: 0.5,
    hue: 28,
  },
  {
    id: "renaissance",
    name: "Consort Renaissance",
    era: "Renaissance",
    years: "1400–1600",
    region: "Europe",
    description: "Luth et flûtes en contrepoint délicat, danses de cour, douceur polyphonique.",
    keywords: ["renaissance", "luth", "cour", "pavane", "galliarde", "polyphonie"],
    bpm: [84, 108],
    scales: ["major", "dorian"],
    progressions: ["folk", "baroque"],
    drums: ["none"],
    instruments: { melody: ["flute", "harp"], chords: ["nylonGuitar", "harp"], bass: ["uprightBass"] },
    chordStyle: ["arpeggiated", "strummed"],
    bassStyle: ["root"],
    structures: ["throughComposed"],
    vocalStyle: "lead",
    energy: 0.3,
    hue: 45,
  },
  {
    id: "baroque",
    name: "Baroque",
    era: "Baroque",
    years: "1600–1750",
    region: "Europe",
    description: "Clavecin volubile, basse continue, cycles de quintes et ornements — l'horlogerie de Bach et Vivaldi.",
    keywords: ["baroque", "bach", "vivaldi", "clavecin", "fugue", "concerto"],
    bpm: [92, 120],
    scales: ["major", "harmonicMinor"],
    progressions: ["baroque"],
    drums: ["none"],
    instruments: { melody: ["violin", "harpsichord"], chords: ["harpsichord"], bass: ["uprightBass"], arp: ["harpsichord"] },
    chordStyle: ["arpeggiated", "alberti"],
    bassStyle: ["walking", "root"],
    arpChance: 0.8,
    structures: ["throughComposed"],
    vocalStyle: "none",
    energy: 0.55,
    hue: 50,
  },
  {
    id: "classical",
    name: "Classique",
    era: "Période classique",
    years: "1750–1820",
    region: "Europe",
    description: "Élégance viennoise : piano en basse d'Alberti, cordes limpides, phrases en questions-réponses.",
    keywords: ["classique", "mozart", "haydn", "sonate", "symphonie", "vienne"],
    bpm: [100, 132],
    scales: ["major", "naturalMinor"],
    progressions: ["baroque", "folk"],
    drums: ["none"],
    instruments: { melody: ["piano", "violin"], chords: ["piano"], bass: ["uprightBass"], pad: ["strings"] },
    chordStyle: ["alberti"],
    bassStyle: ["root"],
    padChance: 0.6,
    structures: ["throughComposed"],
    vocalStyle: "none",
    energy: 0.45,
    hue: 210,
  },
  {
    id: "romantic",
    name: "Romantique",
    era: "Romantisme",
    years: "1820–1900",
    region: "Europe",
    description: "Piano ardent et cordes en houle, grands crescendos, harmonies qui chavirent — Chopin, Brahms.",
    keywords: ["romantique", "chopin", "nocturne", "passion", "piano solo", "brahms", "liszt"],
    bpm: [66, 88],
    scales: ["naturalMinor", "harmonicMinor", "major"],
    progressions: ["minorPop", "epic"],
    drums: ["none"],
    instruments: { melody: ["piano", "violin"], chords: ["piano"], pad: ["strings"], bass: ["uprightBass"] },
    chordStyle: ["arpeggiated", "sustained"],
    bassStyle: ["root", "octaves"],
    padChance: 0.8,
    structures: ["throughComposed"],
    vocalStyle: "none",
    energy: 0.4,
    hue: 340,
  },
  {
    id: "impressionist",
    name: "Impressionniste",
    era: "Fin XIXe",
    years: "1890–1925",
    region: "France",
    description: "Brumes harmoniques de Debussy et Satie : gammes par tons, accords flottants, lumière diffuse.",
    keywords: ["impressionniste", "debussy", "satie", "ravel", "gymnopédie", "rêverie", "brume"],
    bpm: [60, 80],
    scales: ["lydian", "wholeTone", "major"],
    progressions: ["modalDrone", "folk"],
    drums: ["none"],
    instruments: { melody: ["piano", "harp"], chords: ["piano"], pad: ["padGlass", "strings"], bass: ["uprightBass"] },
    chordStyle: ["sustained", "arpeggiated"],
    bassStyle: ["root"],
    padChance: 0.9,
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.2,
    hue: 195,
  },
  {
    id: "waltz",
    name: "Valse viennoise",
    era: "XIXe siècle",
    years: "1820–1900",
    region: "Autriche",
    description: "Trois temps tourbillonnants, oum-pah-pah des cordes, bals dorés de Vienne.",
    keywords: ["valse", "waltz", "bal", "vienne", "trois temps", "strauss"],
    bpm: [130, 170],
    stepsPerBar: 12,
    scales: ["major"],
    progressions: ["folk", "doowop"],
    drums: ["waltz"],
    instruments: { melody: ["violin", "piano"], chords: ["strings", "piano"], bass: ["uprightBass"], pad: ["strings"] },
    chordStyle: ["offbeat"],
    bassStyle: ["root"],
    structures: ["throughComposed"],
    vocalStyle: "none",
    energy: 0.55,
    hue: 48,
  },
  {
    id: "flamenco",
    name: "Flamenco",
    era: "Tradition andalouse",
    years: "XVIIIe–aujourd'hui",
    region: "Espagne",
    description: "Guitare nylon incandescente, cadence andalouse, palmas et duende phrygien.",
    keywords: ["flamenco", "espagnol", "gitane", "andalousie", "guitare espagnole", "duende"],
    bpm: [110, 140],
    scales: ["phrygianDominant", "phrygian"],
    progressions: ["andalusian"],
    drums: ["bossa"],
    instruments: { melody: ["nylonGuitar"], chords: ["nylonGuitar"], bass: ["uprightBass"] },
    chordStyle: ["strummed"],
    bassStyle: ["root"],
    structures: ["throughComposed"],
    vocalStyle: "lead",
    energy: 0.7,
    hue: 14,
  },
  {
    id: "raga",
    name: "Raga hindustani",
    era: "Tradition indienne",
    years: "Antiquité–aujourd'hui",
    region: "Inde",
    description: "Sitar en méandres sur bourdon de tanpura, tabla en cycles, ascension méditative.",
    keywords: ["raga", "inde", "sitar", "tabla", "méditation indienne", "bollywood", "hindustani"],
    bpm: [70, 95],
    scales: ["ragaBhairav", "dorian", "mixolydian"],
    progressions: ["modalDrone"],
    drums: ["tabla"],
    instruments: { melody: ["sitar"], drone: ["tanpura"], chords: ["tanpura"] },
    chordStyle: ["sustained"],
    bassStyle: ["drone"],
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.35,
    hue: 30,
  },
  {
    id: "gamelan",
    name: "Gamelan",
    era: "Tradition javanaise",
    years: "VIIIe siècle–aujourd'hui",
    region: "Indonésie",
    description: "Métallophones en cascade, gongs profonds, cycles entrelacés aux gammes slendro et pelog.",
    keywords: ["gamelan", "bali", "java", "indonésie", "gong", "temple"],
    bpm: [80, 110],
    scales: ["slendro", "pelog"],
    progressions: ["modalDrone"],
    drums: ["gamelan"],
    instruments: { melody: ["gamelanMetal"], chords: ["gamelanMetal"], arp: ["gamelanMetal"], bass: ["subBass"] },
    chordStyle: ["pulsing"],
    bassStyle: ["drone"],
    arpChance: 1,
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.4,
    hue: 160,
  },
  {
    id: "koto",
    name: "Koto japonais",
    era: "Tradition japonaise",
    years: "VIIIe siècle–aujourd'hui",
    region: "Japon",
    description: "Cordes pincées du koto, silences habités, gammes hirajoshi sous les cerisiers.",
    keywords: ["japon", "koto", "zen", "sakura", "cerisier", "japonais", "shamisen"],
    bpm: [60, 84],
    scales: ["hirajoshi", "inSen"],
    progressions: ["modalDrone"],
    drums: ["none"],
    instruments: { melody: ["koto"], chords: ["koto"], pad: ["padGlass"], bass: ["uprightBass"] },
    chordStyle: ["arpeggiated"],
    bassStyle: ["root"],
    padChance: 0.5,
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.2,
    hue: 330,
  },
  {
    id: "celtic",
    name: "Folk celtique",
    era: "Tradition celtique",
    years: "Tradition–aujourd'hui",
    region: "Irlande / Bretagne",
    description: "Gigue de flûte et violon, harpe ruisselante, vert des collines et tavernes de Dublin.",
    keywords: ["celtique", "irlandais", "gigue", "dublin", "harpe", "breton", "taverne"],
    bpm: [110, 132],
    scales: ["dorian", "mixolydian", "major"],
    progressions: ["folk"],
    drums: ["march"],
    instruments: { melody: ["flute", "violin"], chords: ["nylonGuitar", "harp"], bass: ["uprightBass"], arp: ["harp"] },
    chordStyle: ["strummed"],
    bassStyle: ["rootFifth"],
    arpChance: 0.5,
    structures: ["throughComposed"],
    vocalStyle: "lead",
    energy: 0.6,
    hue: 130,
  },
  {
    id: "mariachi",
    name: "Mariachi",
    era: "Tradition mexicaine",
    years: "XIXe–aujourd'hui",
    region: "Mexique",
    description: "Trompettes fières, guitarrón, vihuela en contretemps — fête et fierté de Guadalajara.",
    keywords: ["mariachi", "mexique", "trompette", "fiesta", "ranchera", "guadalajara"],
    bpm: [120, 150],
    stepsPerBar: 12,
    scales: ["major"],
    progressions: ["folk", "doowop"],
    drums: ["waltz"],
    instruments: { melody: ["trumpet", "violin"], chords: ["nylonGuitar"], bass: ["uprightBass"] },
    chordStyle: ["offbeat"],
    bassStyle: ["rootFifth"],
    structures: ["songShort"],
    vocalStyle: "lead",
    energy: 0.7,
    hue: 20,
  },
  {
    id: "tango",
    name: "Tango",
    era: "Début XXe",
    years: "1880–aujourd'hui",
    region: "Argentine",
    description: "Bandonéon dramatique, marcato tranchant, élégance sombre des milongas de Buenos Aires.",
    keywords: ["tango", "argentine", "bandonéon", "buenos aires", "milonga", "piazzolla"],
    bpm: [110, 128],
    scales: ["harmonicMinor", "naturalMinor"],
    progressions: ["minorPop", "andalusian"],
    drums: ["march"],
    instruments: { melody: ["accordion", "violin"], chords: ["accordion", "piano"], bass: ["uprightBass"] },
    chordStyle: ["stabs"],
    bassStyle: ["root"],
    structures: ["throughComposed"],
    vocalStyle: "lead",
    energy: 0.6,
    hue: 0,
  },
  {
    id: "delta-blues",
    name: "Delta blues",
    era: "Début XXe",
    years: "1900–1940",
    region: "Mississippi, USA",
    description: "Douze mesures poussiéreuses, guitare slide, gamme blues et complaintes du Delta.",
    keywords: ["blues", "delta", "mississippi", "slide", "douze mesures", "muddy"],
    bpm: [72, 96],
    swing: 0.45,
    scales: ["blues", "minorPentatonic"],
    progressions: ["blues12"],
    drums: ["backbeat"],
    instruments: { melody: ["steelGuitar"], chords: ["steelGuitar"], bass: ["uprightBass"] },
    chordStyle: ["comping"],
    bassStyle: ["walking", "root"],
    structures: ["blues"],
    vocalStyle: "lead",
    energy: 0.45,
    hue: 220,
  },
  {
    id: "ragtime",
    name: "Ragtime",
    era: "1900s",
    years: "1895–1920",
    region: "USA",
    description: "Piano sautillant, main gauche en pompe, syncopes joyeuses de Scott Joplin.",
    keywords: ["ragtime", "joplin", "saloon", "piano bastringue", "1900"],
    bpm: [96, 116],
    scales: ["major"],
    progressions: ["baroque", "doowop"],
    drums: ["none"],
    instruments: { melody: ["piano"], chords: ["piano"], bass: ["piano"] },
    chordStyle: ["offbeat"],
    bassStyle: ["octaves"],
    structures: ["throughComposed"],
    vocalStyle: "none",
    energy: 0.6,
    hue: 40,
  },
  {
    id: "swing",
    name: "Swing / Big band",
    era: "Années 1930-40",
    years: "1930–1945",
    region: "USA",
    description: "Cuivres rutilants, ride chaloupée, walking bass — les grandes salles de bal en ébullition.",
    keywords: ["swing", "big band", "jazz 1940", "ellington", "bal", "charleston"],
    bpm: [130, 170],
    swing: 0.55,
    scales: ["major", "mixolydian"],
    progressions: ["jazz", "doowop"],
    drums: ["swingJazz"],
    instruments: { melody: ["trumpet", "sax"], chords: ["brass", "piano"], bass: ["uprightBass"] },
    chordStyle: ["stabs", "comping"],
    bassStyle: ["walking"],
    structures: ["jazz"],
    vocalStyle: "lead",
    energy: 0.75,
    hue: 45,
  },
  {
    id: "cool-jazz",
    name: "Jazz cool",
    era: "Années 1950",
    years: "1949–1965",
    region: "USA",
    description: "Piano feutré, contrebasse veloutée, balais sur la caisse claire — minuit, fumée et trompette sourde.",
    keywords: ["jazz", "cool", "miles", "club", "minuit", "lounge", "smooth"],
    bpm: [80, 110],
    swing: 0.55,
    scales: ["dorian", "major", "mixolydian"],
    progressions: ["jazz"],
    drums: ["swingJazz"],
    instruments: { melody: ["trumpet", "sax", "epiano"], chords: ["piano", "epiano"], bass: ["uprightBass"] },
    chordStyle: ["comping"],
    bassStyle: ["walking"],
    structures: ["jazz"],
    vocalStyle: "lead",
    energy: 0.35,
    hue: 230,
  },
  {
    id: "bossa",
    name: "Bossa nova",
    era: "Années 1950-60",
    years: "1958–1970",
    region: "Brésil",
    description: "Guitare nylon en clave feutrée, harmonies riches, brise d'Ipanema.",
    keywords: ["bossa", "brésil", "ipanema", "jobim", "plage", "rio", "samba douce"],
    bpm: [120, 140],
    scales: ["major", "lydian"],
    progressions: ["jazz"],
    drums: ["bossa"],
    instruments: { melody: ["nylonGuitar", "flute"], chords: ["nylonGuitar", "epiano"], bass: ["fingerBass"] },
    chordStyle: ["comping"],
    bassStyle: ["rootFifth"],
    structures: ["songShort"],
    vocalStyle: "lead",
    energy: 0.4,
    hue: 95,
  },
  {
    id: "soul",
    name: "Soul / Motown",
    era: "Années 1960",
    years: "1960–1975",
    region: "USA",
    description: "Groove Motown, piano électrique chaleureux, cuivres en réponse, ferveur gospel.",
    keywords: ["soul", "motown", "gospel", "aretha", "stax", "rétro 60s"],
    bpm: [88, 112],
    scales: ["major", "mixolydian"],
    progressions: ["doowop", "pop"],
    drums: ["backbeat"],
    instruments: { melody: ["epiano", "sax"], chords: ["epiano", "organ"], bass: ["fingerBass"], pad: ["brass"] },
    chordStyle: ["comping", "stabs"],
    bassStyle: ["syncopated"],
    padChance: 0.5,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.65,
    hue: 35,
  },
  {
    id: "rock",
    name: "Rock classique",
    era: "Années 1960-70",
    years: "1965–1980",
    region: "UK / USA",
    description: "Guitares saturées, batterie carrée, refrains à reprendre poing levé.",
    keywords: ["rock", "guitare électrique", "stadium", "70s", "riff", "led"],
    bpm: [110, 140],
    scales: ["minorPentatonic", "mixolydian", "major"],
    progressions: ["pop", "folk"],
    drums: ["backbeat"],
    instruments: { melody: ["distGuitar"], chords: ["distGuitar", "organ"], bass: ["fingerBass"] },
    chordStyle: ["strummed", "stabs"],
    bassStyle: ["root", "octaves"],
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.85,
    hue: 8,
  },
  {
    id: "funk",
    name: "Funk",
    era: "Années 1970",
    years: "1968–1982",
    region: "USA",
    description: "Basse qui claque, guitare wah en doubles-croches, cuivres tranchants — tout est dans le « one ».",
    keywords: ["funk", "groove", "james brown", "wah", "disco funk", "70s"],
    bpm: [96, 116],
    scales: ["dorian", "minorPentatonic", "mixolydian"],
    progressions: ["modalDrone", "jazz"],
    drums: ["afrobeat", "backbeat"],
    instruments: { melody: ["epiano", "sax"], chords: ["epiano", "brass"], bass: ["fingerBass"] },
    chordStyle: ["stabs"],
    bassStyle: ["syncopated"],
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.8,
    hue: 285,
  },
  {
    id: "afrobeat",
    name: "Afrobeat",
    era: "Années 1970",
    years: "1968–aujourd'hui",
    region: "Nigeria / Ghana",
    description: "Polyrythmie hypnotique de Lagos : cloche, guitares entrelacées, cuivres et transe de Fela.",
    keywords: ["afrobeat", "fela", "lagos", "afrique", "polyrythmie", "highlife"],
    bpm: [100, 124],
    scales: ["dorian", "mixolydian", "minorPentatonic"],
    progressions: ["modalDrone"],
    drums: ["afrobeat"],
    instruments: { melody: ["sax", "trumpet"], chords: ["epiano", "steelGuitar"], bass: ["fingerBass"], arp: ["steelGuitar"] },
    chordStyle: ["stabs"],
    bassStyle: ["syncopated"],
    arpChance: 0.7,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.75,
    hue: 55,
  },
  {
    id: "reggae",
    name: "Reggae",
    era: "Années 1970",
    years: "1968–aujourd'hui",
    region: "Jamaïque",
    description: "Skank en contretemps, one-drop nonchalant, basse ronde sous le soleil de Kingston.",
    keywords: ["reggae", "jamaïque", "marley", "rasta", "skank", "kingston", "dub"],
    bpm: [70, 90],
    scales: ["major", "naturalMinor"],
    progressions: ["folk", "minorPop"],
    drums: ["reggaeOneDrop"],
    instruments: { melody: ["organ", "leadPluck"], chords: ["organ", "steelGuitar"], bass: ["fingerBass"] },
    chordStyle: ["offbeat"],
    bassStyle: ["syncopated"],
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.5,
    hue: 120,
  },
  {
    id: "disco",
    name: "Disco",
    era: "Années 1970",
    years: "1974–1982",
    region: "USA / Europe",
    description: "Four-on-the-floor scintillant, basse en octaves, cordes filées et boule à facettes.",
    keywords: ["disco", "dancefloor", "boule à facettes", "studio 54", "funky 70s"],
    bpm: [112, 126],
    scales: ["naturalMinor", "dorian", "major"],
    progressions: ["minorPop", "pop"],
    drums: ["fourFloor"],
    instruments: { melody: ["strings", "leadSaw"], chords: ["epiano", "strings"], bass: ["fingerBass"], pad: ["strings"], arp: ["leadPluck"] },
    chordStyle: ["stabs", "offbeat"],
    bassStyle: ["octaves"],
    padChance: 0.7,
    arpChance: 0.4,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.8,
    hue: 310,
  },
  {
    id: "synthwave",
    name: "Synthwave",
    era: "Années 1980 (revival)",
    years: "1980s / 2010s",
    region: "Monde",
    description: "Néons et chrome : nappes analogiques, basse pulsée, arpèges nocturnes, gated reverb.",
    keywords: ["synthwave", "retrowave", "néon", "80s", "outrun", "nuit", "vhs", "cyberpunk"],
    bpm: [84, 108],
    scales: ["naturalMinor", "dorian"],
    progressions: ["minorPop", "pop"],
    drums: ["backbeat", "halftime"],
    instruments: { melody: ["leadSaw", "leadSquare"], chords: ["padWarm"], bass: ["subBass", "pluckBass"], pad: ["padWarm"], arp: ["leadPluck"] },
    chordStyle: ["pulsing", "sustained"],
    bassStyle: ["octaves", "root"],
    padChance: 0.9,
    arpChance: 0.85,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.6,
    hue: 300,
  },
  {
    id: "chiptune",
    name: "Chiptune 8-bit",
    era: "Années 1980",
    years: "1983–aujourd'hui",
    region: "Japon / Monde",
    description: "Carrés et triangles de console, arpèges frénétiques, mélodies de cartouche inoubliables.",
    keywords: ["chiptune", "8-bit", "jeu vidéo", "rétro gaming", "nes", "pixel"],
    bpm: [120, 150],
    scales: ["major", "naturalMinor"],
    progressions: ["pop", "minorPop"],
    drums: ["backbeat"],
    instruments: { melody: ["leadChip"], chords: ["leadSquare"], bass: ["leadSquare"], arp: ["leadChip"] },
    chordStyle: ["pulsing"],
    bassStyle: ["octaves"],
    arpChance: 0.9,
    structures: ["songShort"],
    vocalStyle: "none",
    energy: 0.75,
    hue: 145,
  },
  {
    id: "house",
    name: "House",
    era: "Années 1980-90",
    years: "1985–aujourd'hui",
    region: "Chicago",
    description: "Kick quatre-quatre, stabs de piano, hats ouverts en contretemps — la chaleur des clubs de Chicago.",
    keywords: ["house", "club", "chicago", "deep house", "piano house", "dancefloor"],
    bpm: [120, 128],
    scales: ["naturalMinor", "dorian"],
    progressions: ["minorPop", "jazz"],
    drums: ["fourFloor"],
    instruments: { melody: ["epiano", "leadSaw"], chords: ["piano", "epiano"], bass: ["pluckBass"], pad: ["padWarm"] },
    chordStyle: ["stabs", "offbeat"],
    bassStyle: ["syncopated", "octaves"],
    padChance: 0.6,
    structures: ["edm"],
    vocalStyle: "lead",
    energy: 0.75,
    hue: 265,
  },
  {
    id: "techno",
    name: "Techno",
    era: "Années 1990",
    years: "1988–aujourd'hui",
    region: "Détroit / Berlin",
    description: "Machine hypnotique : kick sombre, séquences acides, montée implacable des warehouses.",
    keywords: ["techno", "berlin", "détroit", "rave", "warehouse", "acid", "industriel"],
    bpm: [128, 140],
    scales: ["naturalMinor", "phrygian"],
    progressions: ["modalDrone"],
    drums: ["fourFloor"],
    instruments: { melody: ["leadSaw"], chords: ["padWarm"], bass: ["subBass", "pluckBass"], arp: ["leadPluck"], pad: ["padWarm"] },
    chordStyle: ["pulsing"],
    bassStyle: ["root", "octaves"],
    arpChance: 0.9,
    padChance: 0.5,
    structures: ["edm"],
    vocalStyle: "none",
    energy: 0.85,
    hue: 350,
  },
  {
    id: "trance",
    name: "Trance",
    era: "Années 1990-2000",
    years: "1993–aujourd'hui",
    region: "Europe",
    description: "Supersaw céleste, arpèges en rouleaux, breakdown émotif puis envol — mains vers le ciel.",
    keywords: ["trance", "uplifting", "ibiza", "supersaw", "festival", "envol"],
    bpm: [132, 140],
    scales: ["naturalMinor"],
    progressions: ["minorPop", "epic"],
    drums: ["fourFloor"],
    instruments: { melody: ["leadSaw"], chords: ["padWarm"], bass: ["pluckBass"], arp: ["leadPluck"], pad: ["padGlass"] },
    chordStyle: ["pulsing"],
    bassStyle: ["octaves"],
    arpChance: 1,
    padChance: 0.9,
    structures: ["edm"],
    vocalStyle: "lead",
    energy: 0.85,
    hue: 200,
  },
  {
    id: "ambient",
    name: "Ambient",
    era: "Années 1970-aujourd'hui",
    years: "1975–aujourd'hui",
    region: "Monde",
    description: "Paysages sonores en suspension, nappes qui respirent, temps dilaté — Eno en apesanteur.",
    keywords: ["ambient", "méditation", "espace", "calme", "drone", "planant", "sommeil", "relaxation"],
    bpm: [56, 72],
    scales: ["lydian", "major", "dorian"],
    progressions: ["modalDrone", "folk"],
    drums: ["none"],
    instruments: { melody: ["padGlass", "bell"], chords: ["padWarm"], pad: ["padWarm", "padGlass"], bass: ["subBass"], arp: ["bell"] },
    chordStyle: ["sustained"],
    bassStyle: ["drone"],
    padChance: 1,
    arpChance: 0.4,
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.1,
    hue: 185,
  },
  {
    id: "boombap",
    name: "Hip-hop boom bap",
    era: "Années 1990",
    years: "1988–2000",
    region: "New York",
    description: "Batterie qui cogne et swingue, samples jazz poussiéreux, basse ronde — l'âge d'or du rap East Coast.",
    keywords: ["hip-hop", "rap", "boom bap", "90s", "new york", "golden age", "mpc"],
    bpm: [86, 96],
    swing: 0.3,
    scales: ["dorian", "minorPentatonic"],
    progressions: ["jazz", "minorPop"],
    drums: ["boomBap"],
    instruments: { melody: ["epiano", "trumpet"], chords: ["epiano", "piano"], bass: ["fingerBass", "subBass"] },
    chordStyle: ["comping"],
    bassStyle: ["root", "syncopated"],
    structures: ["songShort"],
    vocalStyle: "lead",
    energy: 0.6,
    hue: 25,
  },
  {
    id: "trap",
    name: "Trap",
    era: "Années 2010",
    years: "2010–aujourd'hui",
    region: "Atlanta",
    description: "808 qui glisse, hi-hats en rafales, nappes sombres — l'ossature du rap moderne.",
    keywords: ["trap", "808", "rap moderne", "atlanta", "drill", "hi-hats"],
    bpm: [130, 150],
    scales: ["harmonicMinor", "naturalMinor", "phrygian"],
    progressions: ["minorPop", "modalDrone"],
    drums: ["trap"],
    instruments: { melody: ["bell", "leadSquare"], chords: ["padWarm", "padChoir"], bass: ["bass808"], pad: ["padChoir"] },
    chordStyle: ["sustained"],
    bassStyle: ["sub"],
    padChance: 0.8,
    structures: ["songShort"],
    vocalStyle: "lead",
    energy: 0.7,
    hue: 270,
  },
  {
    id: "reggaeton",
    name: "Reggaeton",
    era: "Années 2000",
    years: "1995–aujourd'hui",
    region: "Porto Rico",
    description: "Dembow contagieux, basses chaudes, mélodies accrocheuses — perreo de San Juan au monde entier.",
    keywords: ["reggaeton", "latino", "dembow", "perreo", "porto rico", "été"],
    bpm: [88, 100],
    scales: ["naturalMinor", "dorian"],
    progressions: ["minorPop", "doowop"],
    drums: ["dembow"],
    instruments: { melody: ["leadPluck", "marimba"], chords: ["padWarm", "epiano"], bass: ["subBass"], pad: ["padWarm"] },
    chordStyle: ["offbeat", "stabs"],
    bassStyle: ["root"],
    padChance: 0.6,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.75,
    hue: 15,
  },
  {
    id: "lofi",
    name: "Lo-fi hip-hop",
    era: "Années 2010",
    years: "2015–aujourd'hui",
    region: "Internet",
    description: "Boucles feutrées, piano voilé, craquements de vinyle — pour réviser sous la pluie.",
    keywords: ["lofi", "lo-fi", "chill", "étude", "pluie", "café", "détente", "beats to relax"],
    bpm: [70, 86],
    swing: 0.3,
    scales: ["dorian", "major", "lydian"],
    progressions: ["jazz"],
    drums: ["boomBap"],
    instruments: { melody: ["epiano", "kalimba"], chords: ["epiano", "piano"], bass: ["fingerBass"], pad: ["padWarm"] },
    chordStyle: ["comping", "sustained"],
    bassStyle: ["root"],
    padChance: 0.5,
    structures: ["ambient"],
    vocalStyle: "none",
    energy: 0.25,
    hue: 35,
  },
  {
    id: "kpop",
    name: "Pop moderne / K-pop",
    era: "Années 2010-20",
    years: "2012–aujourd'hui",
    region: "Monde / Corée",
    description: "Production maximaliste : drop scintillant, hooks ciselés, synthés éclatants et précision chirurgicale.",
    keywords: ["pop", "k-pop", "kpop", "hit", "radio", "dance pop", "moderne", "catchy"],
    bpm: [100, 126],
    scales: ["major", "naturalMinor"],
    progressions: ["pop", "minorPop"],
    drums: ["backbeat", "fourFloor"],
    instruments: { melody: ["leadSaw", "leadPluck"], chords: ["piano", "padWarm"], bass: ["subBass", "pluckBass"], pad: ["padWarm"], arp: ["leadPluck"] },
    chordStyle: ["stabs", "pulsing"],
    bassStyle: ["octaves", "syncopated"],
    padChance: 0.7,
    arpChance: 0.5,
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.8,
    hue: 320,
  },
  {
    id: "epic",
    name: "Épique cinématique",
    era: "Musique de film",
    years: "1977–aujourd'hui",
    region: "Hollywood",
    description: "Cordes en ostinato, cuivres héroïques, chœurs et percussions de guerre — bande-annonce garantie.",
    keywords: ["épique", "cinématique", "film", "trailer", "héroïque", "bataille", "orchestre", "zimmer"],
    bpm: [90, 120],
    scales: ["naturalMinor", "harmonicMinor", "dorian"],
    progressions: ["epic", "minorPop"],
    drums: ["march", "halftime"],
    instruments: { melody: ["brass", "violin"], chords: ["staccatoStrings", "strings"], bass: ["subBass", "uprightBass"], pad: ["padChoir", "strings"], arp: ["staccatoStrings"] },
    chordStyle: ["pulsing", "sustained"],
    bassStyle: ["octaves", "root"],
    padChance: 0.9,
    arpChance: 0.7,
    structures: ["edm"],
    vocalStyle: "choir",
    energy: 0.85,
    hue: 215,
  },
  {
    id: "metal",
    name: "Heavy metal",
    era: "Années 1980",
    years: "1980–aujourd'hui",
    region: "UK / USA",
    description: "Riffs de plomb, double pédale, gammes sombres — le mur du son qui headbangue.",
    keywords: ["metal", "heavy", "riff", "headbang", "saturé", "puissant", "sombre"],
    bpm: [140, 180],
    scales: ["phrygian", "naturalMinor", "minorPentatonic"],
    progressions: ["andalusian", "minorPop"],
    drums: ["backbeat", "march"],
    instruments: { melody: ["distGuitar", "leadSaw"], chords: ["distGuitar"], bass: ["fingerBass"] },
    chordStyle: ["pulsing", "stabs"],
    bassStyle: ["root", "octaves"],
    structures: ["song"],
    vocalStyle: "lead",
    energy: 0.95,
    hue: 0,
  },
];

export function getGenre(id: string): GenreDef {
  return GENRES.find((g) => g.id === id) ?? GENRES.find((g) => g.id === "kpop")!;
}

/** Score genres against a free-text prompt; returns best match. */
export function matchGenre(prompt: string): { genre: GenreDef; score: number } {
  const p = prompt.toLowerCase();
  let best: GenreDef | null = null;
  let bestScore = 0;
  for (const g of GENRES) {
    let score = 0;
    if (p.includes(g.id)) score += 5;
    if (p.includes(g.name.toLowerCase())) score += 5;
    for (const k of g.keywords) if (p.includes(k.toLowerCase())) score += 3;
    if (score > bestScore) {
      bestScore = score;
      best = g;
    }
  }
  return { genre: best ?? getGenre("kpop"), score: bestScore };
}
