import { OfflineAudioContext } from 'node-web-audio-api';
const ctx = new OfflineAudioContext(2, 44100, 44100);
const o = ctx.createOscillator();
o.frequency.value = 440;
const g = ctx.createGain(); g.gain.value = 0.5;
o.connect(g); g.connect(ctx.destination);
o.start(0); o.stop(1);
console.log('rendering…');
const buf = await ctx.startRendering();
console.log('done', buf.length, buf.getChannelData(0)[1000]);
